# Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/pullmybeardapp.cpp) \
                 $$quote($$BASEDIR/src/soundmanager.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/pullmybeardapp.h) \
                 $$quote($$BASEDIR/src/soundmanager.h)
    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/pullmybeardapp.cpp) \
                 $$quote($$BASEDIR/src/soundmanager.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/pullmybeardapp.h) \
                 $$quote($$BASEDIR/src/soundmanager.h)
    }
}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/pullmybeardapp.cpp) \
                 $$quote($$BASEDIR/src/soundmanager.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/pullmybeardapp.h) \
                 $$quote($$BASEDIR/src/soundmanager.h)
    }
}

INCLUDEPATH +=  $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../src/*.c) \
             $$quote($$BASEDIR/../src/*.c++) \
             $$quote($$BASEDIR/../src/*.cc) \
             $$quote($$BASEDIR/../src/*.cpp) \
             $$quote($$BASEDIR/../src/*.cxx) \
             $$quote($$BASEDIR/../assets/*.qml) \
             $$quote($$BASEDIR/../assets/*.js) \
             $$quote($$BASEDIR/../assets/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/images/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/images/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/images/*.qs) \
             $$quote($$BASEDIR/../assets/images/*.qml) \
             $$quote($$BASEDIR/../assets/images/*.js) \
             $$quote($$BASEDIR/../assets/images/*.qs) \
             $$quote($$BASEDIR/../assets/mindw76h128du/*.qml) \
             $$quote($$BASEDIR/../assets/mindw76h128du/*.js) \
             $$quote($$BASEDIR/../assets/mindw76h128du/*.qs) \
             $$quote($$BASEDIR/../assets/sounds/*.qml) \
             $$quote($$BASEDIR/../assets/sounds/*.js) \
             $$quote($$BASEDIR/../assets/sounds/*.qs)

    HEADERS +=  $$quote($$BASEDIR/../src/*.h) \
             $$quote($$BASEDIR/../src/*.h++) \
             $$quote($$BASEDIR/../src/*.hh) \
             $$quote($$BASEDIR/../src/*.hpp) \
             $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS =  $$quote($${TARGET}.ts)
