# Auto-generated by IDE. All changes by user will be lost!
# Created at 11/1/12 1:52 PM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/pullmybeardapp.cpp \
    $$BASEDIR/src/soundmanager.cpp \
    $$BASEDIR/src/main.cpp \    

HEADERS +=  \
    $$BASEDIR/src/pullmybeardapp.h \
    $$BASEDIR/src/soundmanager.h

CONFIG += precompile_header
PRECOMPILED_HEADER = $$BASEDIR/precompiled.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

