# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/cascadescookbookapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/recipeitem.cpp) \
                 $$quote($$BASEDIR/src/recipeitemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/intro.cpp) \
                 $$quote($$BASEDIR/src/recipes/labelrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruittemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.cpp) \
                 $$quote($$BASEDIR/src/uivalues.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/cascadescookbookapp.h) \
                 $$quote($$BASEDIR/src/recipeitem.h) \
                 $$quote($$BASEDIR/src/recipeitemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/intro.h) \
                 $$quote($$BASEDIR/src/recipes/labelrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.h) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe.h) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.h) \
                 $$quote($$BASEDIR/src/uivalues.h)

    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/cascadescookbookapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/recipeitem.cpp) \
                 $$quote($$BASEDIR/src/recipeitemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/intro.cpp) \
                 $$quote($$BASEDIR/src/recipes/labelrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruittemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.cpp) \
                 $$quote($$BASEDIR/src/uivalues.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/cascadescookbookapp.h) \
                 $$quote($$BASEDIR/src/recipeitem.h) \
                 $$quote($$BASEDIR/src/recipeitemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/intro.h) \
                 $$quote($$BASEDIR/src/recipes/labelrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.h) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe.h) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.h) \
                 $$quote($$BASEDIR/src/uivalues.h)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/cascadescookbookapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/recipeitem.cpp) \
                 $$quote($$BASEDIR/src/recipeitemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/intro.cpp) \
                 $$quote($$BASEDIR/src/recipes/labelrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruittemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.cpp) \
                 $$quote($$BASEDIR/src/uivalues.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/cascadescookbookapp.h) \
                 $$quote($$BASEDIR/src/recipeitem.h) \
                 $$quote($$BASEDIR/src/recipeitemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/intro.h) \
                 $$quote($$BASEDIR/src/recipes/labelrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.h) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe.h) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.h) \
                 $$quote($$BASEDIR/src/uivalues.h)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/recipes) \
         $$quote($$BASEDIR/src/recipes/sheetrecipe) \
         $$quote($$BASEDIR/src/recipes/selectionrecipe) \
         $$quote($$BASEDIR/src/recipes/customdialogrecipe) \
         $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}.ts)

