# Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/cascadescookbookapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/recipeitem.cpp) \
                 $$quote($$BASEDIR/src/recipeitemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/accessabilityrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/activityindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/inlineactivityindicator.cpp) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/customitemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/custompickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gridlayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/intro.cpp) \
                 $$quote($$BASEDIR/src/recipes/invocationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruittemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelist.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitem.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurverecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/textstylerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/themeswitchrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.cpp) \
                 $$quote($$BASEDIR/src/uivalues.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/cascadescookbookapp.h) \
                 $$quote($$BASEDIR/src/recipeitem.h) \
                 $$quote($$BASEDIR/src/recipeitemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/accessabilityrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/activityindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/inlineactivityindicator.h) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/customitemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/custompickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gridlayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/intro.h) \
                 $$quote($$BASEDIR/src/recipes/invocationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.h) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelist.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitem.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurverecipe.h) \
                 $$quote($$BASEDIR/src/recipes/textstylerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/themeswitchrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.h) \
                 $$quote($$BASEDIR/src/uivalues.h)
    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/cascadescookbookapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/recipeitem.cpp) \
                 $$quote($$BASEDIR/src/recipeitemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/accessabilityrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/activityindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/inlineactivityindicator.cpp) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/customitemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/custompickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gridlayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/intro.cpp) \
                 $$quote($$BASEDIR/src/recipes/invocationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruittemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelist.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitem.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurverecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/textstylerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/themeswitchrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.cpp) \
                 $$quote($$BASEDIR/src/uivalues.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/cascadescookbookapp.h) \
                 $$quote($$BASEDIR/src/recipeitem.h) \
                 $$quote($$BASEDIR/src/recipeitemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/accessabilityrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/activityindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/inlineactivityindicator.h) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/customitemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/custompickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gridlayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/intro.h) \
                 $$quote($$BASEDIR/src/recipes/invocationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.h) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelist.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitem.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurverecipe.h) \
                 $$quote($$BASEDIR/src/recipes/textstylerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/themeswitchrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.h) \
                 $$quote($$BASEDIR/src/uivalues.h)
    }
}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/cascadescookbookapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp) \
                 $$quote($$BASEDIR/src/recipeitem.cpp) \
                 $$quote($$BASEDIR/src/recipeitemfactory.cpp) \
                 $$quote($$BASEDIR/src/recipes/accessabilityrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/activityindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/inlineactivityindicator.cpp) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.cpp) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/customitemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/custompickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/gridlayoutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/intro.cpp) \
                 $$quote($$BASEDIR/src/recipes/invocationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.cpp) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruittemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelist.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitem.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitemprovider.cpp) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurverecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/textstylerecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/themeswitchrecipe.cpp) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.cpp) \
                 $$quote($$BASEDIR/src/uivalues.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/cascadescookbookapp.h) \
                 $$quote($$BASEDIR/src/recipeitem.h) \
                 $$quote($$BASEDIR/src/recipeitemfactory.h) \
                 $$quote($$BASEDIR/src/recipes/accessabilityrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/activityindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/activityindicatorrecipe/inlineactivityindicator.h) \
                 $$quote($$BASEDIR/src/recipes/animationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/buttonrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/colorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogalarm.h) \
                 $$quote($$BASEDIR/src/recipes/customdialogrecipe/customdialogrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/customitemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/custompickerrecipe/custompickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/datetimepickerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/docklayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/dropdownrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gesturehandlerrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/gridlayoutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagepaintrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/imagerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/inputrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/intro.h) \
                 $$quote($$BASEDIR/src/recipes/invocationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/menurecipe.h) \
                 $$quote($$BASEDIR/src/recipes/nineslicerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/orientationrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/pixelbufferrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/progressindicatorrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/richtextrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/segmentedcontrolrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selection.h) \
                 $$quote($$BASEDIR/src/recipes/selectionrecipe/selectioncheckbox.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititem.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/fruititemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/sheetrecipe/sheetrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/shortcutrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/sliderrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelist.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitem.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurvelistitemprovider.h) \
                 $$quote($$BASEDIR/src/recipes/stockcurverecipe/stockcurverecipe.h) \
                 $$quote($$BASEDIR/src/recipes/textstylerecipe.h) \
                 $$quote($$BASEDIR/src/recipes/themeswitchrecipe.h) \
                 $$quote($$BASEDIR/src/recipes/webviewrecipe.h) \
                 $$quote($$BASEDIR/src/uivalues.h)
    }
}

INCLUDEPATH +=  $$quote($$BASEDIR/src/recipes/custompickerrecipe) \
         $$quote($$BASEDIR/src/recipes/stockcurverecipe) \
         $$quote($$BASEDIR/src/recipes) \
         $$quote($$BASEDIR/src/recipes/sheetrecipe) \
         $$quote($$BASEDIR/src/recipes/selectionrecipe) \
         $$quote($$BASEDIR/src/recipes/customdialogrecipe) \
         $$quote($$BASEDIR/src) \
         $$quote($$BASEDIR/src/recipes/activityindicatorrecipe)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../src/*.c) \
             $$quote($$BASEDIR/../src/*.c++) \
             $$quote($$BASEDIR/../src/*.cc) \
             $$quote($$BASEDIR/../src/*.cpp) \
             $$quote($$BASEDIR/../src/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/*.c) \
             $$quote($$BASEDIR/../src/recipes/*.c++) \
             $$quote($$BASEDIR/../src/recipes/*.cc) \
             $$quote($$BASEDIR/../src/recipes/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/activityindicatorrecipe/*.c) \
             $$quote($$BASEDIR/../src/recipes/activityindicatorrecipe/*.c++) \
             $$quote($$BASEDIR/../src/recipes/activityindicatorrecipe/*.cc) \
             $$quote($$BASEDIR/../src/recipes/activityindicatorrecipe/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/activityindicatorrecipe/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/customdialogrecipe/*.c) \
             $$quote($$BASEDIR/../src/recipes/customdialogrecipe/*.c++) \
             $$quote($$BASEDIR/../src/recipes/customdialogrecipe/*.cc) \
             $$quote($$BASEDIR/../src/recipes/customdialogrecipe/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/customdialogrecipe/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/custompickerrecipe/*.c) \
             $$quote($$BASEDIR/../src/recipes/custompickerrecipe/*.c++) \
             $$quote($$BASEDIR/../src/recipes/custompickerrecipe/*.cc) \
             $$quote($$BASEDIR/../src/recipes/custompickerrecipe/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/custompickerrecipe/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/selectionrecipe/*.c) \
             $$quote($$BASEDIR/../src/recipes/selectionrecipe/*.c++) \
             $$quote($$BASEDIR/../src/recipes/selectionrecipe/*.cc) \
             $$quote($$BASEDIR/../src/recipes/selectionrecipe/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/selectionrecipe/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/sheetrecipe/*.c) \
             $$quote($$BASEDIR/../src/recipes/sheetrecipe/*.c++) \
             $$quote($$BASEDIR/../src/recipes/sheetrecipe/*.cc) \
             $$quote($$BASEDIR/../src/recipes/sheetrecipe/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/sheetrecipe/*.cxx) \
             $$quote($$BASEDIR/../src/recipes/stockcurverecipe/*.c) \
             $$quote($$BASEDIR/../src/recipes/stockcurverecipe/*.c++) \
             $$quote($$BASEDIR/../src/recipes/stockcurverecipe/*.cc) \
             $$quote($$BASEDIR/../src/recipes/stockcurverecipe/*.cpp) \
             $$quote($$BASEDIR/../src/recipes/stockcurverecipe/*.cxx) \
             $$quote($$BASEDIR/../assets/*.qml) \
             $$quote($$BASEDIR/../assets/*.js) \
             $$quote($$BASEDIR/../assets/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/images/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/images/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/images/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/images/customdialog/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/images/customdialog/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/images/customdialog/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/images/gesturehandler/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/images/gesturehandler/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/images/gesturehandler/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/images/nineslice/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/images/nineslice/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/images/nineslice/*.qs) \
             $$quote($$BASEDIR/../assets/9ppd/images/progressindicator/*.qml) \
             $$quote($$BASEDIR/../assets/9ppd/images/progressindicator/*.js) \
             $$quote($$BASEDIR/../assets/9ppd/images/progressindicator/*.qs) \
             $$quote($$BASEDIR/../assets/images/*.qml) \
             $$quote($$BASEDIR/../assets/images/*.js) \
             $$quote($$BASEDIR/../assets/images/*.qs) \
             $$quote($$BASEDIR/../assets/images/animation/*.qml) \
             $$quote($$BASEDIR/../assets/images/animation/*.js) \
             $$quote($$BASEDIR/../assets/images/animation/*.qs) \
             $$quote($$BASEDIR/../assets/images/button/*.qml) \
             $$quote($$BASEDIR/../assets/images/button/*.js) \
             $$quote($$BASEDIR/../assets/images/button/*.qs) \
             $$quote($$BASEDIR/../assets/images/color/*.qml) \
             $$quote($$BASEDIR/../assets/images/color/*.js) \
             $$quote($$BASEDIR/../assets/images/color/*.qs) \
             $$quote($$BASEDIR/../assets/images/customdialog/*.qml) \
             $$quote($$BASEDIR/../assets/images/customdialog/*.js) \
             $$quote($$BASEDIR/../assets/images/customdialog/*.qs) \
             $$quote($$BASEDIR/../assets/images/custompicker/*.qml) \
             $$quote($$BASEDIR/../assets/images/custompicker/*.js) \
             $$quote($$BASEDIR/../assets/images/custompicker/*.qs) \
             $$quote($$BASEDIR/../assets/images/docklayout/*.qml) \
             $$quote($$BASEDIR/../assets/images/docklayout/*.js) \
             $$quote($$BASEDIR/../assets/images/docklayout/*.qs) \
             $$quote($$BASEDIR/../assets/images/dropdown/*.qml) \
             $$quote($$BASEDIR/../assets/images/dropdown/*.js) \
             $$quote($$BASEDIR/../assets/images/dropdown/*.qs) \
             $$quote($$BASEDIR/../assets/images/gesturehandler/*.qml) \
             $$quote($$BASEDIR/../assets/images/gesturehandler/*.js) \
             $$quote($$BASEDIR/../assets/images/gesturehandler/*.qs) \
             $$quote($$BASEDIR/../assets/images/gridlayout/*.qml) \
             $$quote($$BASEDIR/../assets/images/gridlayout/*.js) \
             $$quote($$BASEDIR/../assets/images/gridlayout/*.qs) \
             $$quote($$BASEDIR/../assets/images/imagepaint/*.qml) \
             $$quote($$BASEDIR/../assets/images/imagepaint/*.js) \
             $$quote($$BASEDIR/../assets/images/imagepaint/*.qs) \
             $$quote($$BASEDIR/../assets/images/items/*.qml) \
             $$quote($$BASEDIR/../assets/images/items/*.js) \
             $$quote($$BASEDIR/../assets/images/items/*.qs) \
             $$quote($$BASEDIR/../assets/images/nineslice/*.qml) \
             $$quote($$BASEDIR/../assets/images/nineslice/*.js) \
             $$quote($$BASEDIR/../assets/images/nineslice/*.qs) \
             $$quote($$BASEDIR/../assets/images/orientation/*.qml) \
             $$quote($$BASEDIR/../assets/images/orientation/*.js) \
             $$quote($$BASEDIR/../assets/images/orientation/*.qs) \
             $$quote($$BASEDIR/../assets/images/picker/*.qml) \
             $$quote($$BASEDIR/../assets/images/picker/*.js) \
             $$quote($$BASEDIR/../assets/images/picker/*.qs) \
             $$quote($$BASEDIR/../assets/images/progressindicator/*.qml) \
             $$quote($$BASEDIR/../assets/images/progressindicator/*.js) \
             $$quote($$BASEDIR/../assets/images/progressindicator/*.qs) \
             $$quote($$BASEDIR/../assets/images/segmentedcontrol/*.qml) \
             $$quote($$BASEDIR/../assets/images/segmentedcontrol/*.js) \
             $$quote($$BASEDIR/../assets/images/segmentedcontrol/*.qs) \
             $$quote($$BASEDIR/../assets/images/sheet/*.qml) \
             $$quote($$BASEDIR/../assets/images/sheet/*.js) \
             $$quote($$BASEDIR/../assets/images/sheet/*.qs) \
             $$quote($$BASEDIR/../assets/images/shortcut/*.qml) \
             $$quote($$BASEDIR/../assets/images/shortcut/*.js) \
             $$quote($$BASEDIR/../assets/images/shortcut/*.qs) \
             $$quote($$BASEDIR/../assets/images/stockcurve/*.qml) \
             $$quote($$BASEDIR/../assets/images/stockcurve/*.js) \
             $$quote($$BASEDIR/../assets/images/stockcurve/*.qs) \
             $$quote($$BASEDIR/../assets/models/*.qml) \
             $$quote($$BASEDIR/../assets/models/*.js) \
             $$quote($$BASEDIR/../assets/models/*.qs)

    HEADERS +=  $$quote($$BASEDIR/../src/*.h) \
             $$quote($$BASEDIR/../src/*.h++) \
             $$quote($$BASEDIR/../src/*.hh) \
             $$quote($$BASEDIR/../src/*.hpp) \
             $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS =  $$quote($${TARGET}.ts)
