# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/720x1280/images/menuicons/icon_browse.png) \
        $$quote($$BASEDIR/assets/720x1280/images/menuicons/icon_continents.png) \
        $$quote($$BASEDIR/assets/720x1280/images/menuicons/icon_favorites.png) \
        $$quote($$BASEDIR/assets/720x1280/images/menuicons/icon_home.png) \
        $$quote($$BASEDIR/assets/720x1280/images/menuicons/icon_info.png) \
        $$quote($$BASEDIR/assets/720x1280/images/menuicons/icon_maxmin.png) \
        $$quote($$BASEDIR/assets/720x720/InfoTab.qml) \
        $$quote($$BASEDIR/assets/720x720/WeatherPage/InlineActivityIndicator.qml) \
        $$quote($$BASEDIR/assets/720x720/images/info/start_cloud.png) \
        $$quote($$BASEDIR/assets/Cities/CitiesPage.qml) \
        $$quote($$BASEDIR/assets/Cities/CityHeader.qml) \
        $$quote($$BASEDIR/assets/Cities/CityItem.qml) \
        $$quote($$BASEDIR/assets/Cities/CityList.qml) \
        $$quote($$BASEDIR/assets/Common/WeatherTitleBar.qml) \
        $$quote($$BASEDIR/assets/ContinentsTab.qml) \
        $$quote($$BASEDIR/assets/FavoriteTab.qml) \
        $$quote($$BASEDIR/assets/InfoTab.qml) \
        $$quote($$BASEDIR/assets/MaxMinTab.qml) \
        $$quote($$BASEDIR/assets/MoreInfoPage.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/CityWeatherPage.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/HomeWeatherPage.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/Weather/InlineActivityIndicator.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/Weather/WeatherItem.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/Weather/WeatherItemContainer.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/Weather/WeatherLoadItem.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/Weather/WeatherPage.qml) \
        $$quote($$BASEDIR/assets/WeatherPages/Weather/WeatherTodayItem.qml) \
        $$quote($$BASEDIR/assets/images/icons/big/0.png) \
        $$quote($$BASEDIR/assets/images/icons/big/0.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/big/1.png) \
        $$quote($$BASEDIR/assets/images/icons/big/1.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/big/2.png) \
        $$quote($$BASEDIR/assets/images/icons/big/2.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/big/3.png) \
        $$quote($$BASEDIR/assets/images/icons/big/3.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/big/4.png) \
        $$quote($$BASEDIR/assets/images/icons/big/4.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/big/5.png) \
        $$quote($$BASEDIR/assets/images/icons/big/5.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/small/0.png) \
        $$quote($$BASEDIR/assets/images/icons/small/0.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/small/1.png) \
        $$quote($$BASEDIR/assets/images/icons/small/1.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/small/2.png) \
        $$quote($$BASEDIR/assets/images/icons/small/2.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/small/3.png) \
        $$quote($$BASEDIR/assets/images/icons/small/3.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/small/4.png) \
        $$quote($$BASEDIR/assets/images/icons/small/4.png.amd) \
        $$quote($$BASEDIR/assets/images/icons/small/5.png) \
        $$quote($$BASEDIR/assets/images/icons/small/5.png.amd) \
        $$quote($$BASEDIR/assets/images/info/start_cloud.png) \
        $$quote($$BASEDIR/assets/images/menuicons/icon_browse.png) \
        $$quote($$BASEDIR/assets/images/menuicons/icon_continents.png) \
        $$quote($$BASEDIR/assets/images/menuicons/icon_favorites.png) \
        $$quote($$BASEDIR/assets/images/menuicons/icon_home.png) \
        $$quote($$BASEDIR/assets/images/menuicons/icon_info.png) \
        $$quote($$BASEDIR/assets/images/menuicons/icon_maxmin.png) \
        $$quote($$BASEDIR/assets/images/pulltorefresh/arrow.png) \
        $$quote($$BASEDIR/assets/main.qml) \
        $$quote($$BASEDIR/assets/models/cities_europe_model.xml) \
        $$quote($$BASEDIR/assets/models/cities_favorites_model.xml) \
        $$quote($$BASEDIR/assets/models/continent_model.xml) \
        $$quote($$BASEDIR/assets/models/json/Alexandria.json) \
        $$quote($$BASEDIR/assets/models/json/Athens.json) \
        $$quote($$BASEDIR/assets/models/json/Bogota.json) \
        $$quote($$BASEDIR/assets/models/json/Brisbane.json) \
        $$quote($$BASEDIR/assets/models/json/Buenos Aires.json) \
        $$quote($$BASEDIR/assets/models/json/Cairo.json) \
        $$quote($$BASEDIR/assets/models/json/Canberra.json) \
        $$quote($$BASEDIR/assets/models/json/Chicago.json) \
        $$quote($$BASEDIR/assets/models/json/Copenhagen.json) \
        $$quote($$BASEDIR/assets/models/json/Johannesburg.json) \
        $$quote($$BASEDIR/assets/models/json/Khartoum.json) \
        $$quote($$BASEDIR/assets/models/json/Kiew.json) \
        $$quote($$BASEDIR/assets/models/json/Kinshasa.json) \
        $$quote($$BASEDIR/assets/models/json/Lagos.json) \
        $$quote($$BASEDIR/assets/models/json/London.json) \
        $$quote($$BASEDIR/assets/models/json/Madrid.json) \
        $$quote($$BASEDIR/assets/models/json/Malm%C3%B6.json) \
        $$quote($$BASEDIR/assets/models/json/McMurdo Station.json) \
        $$quote($$BASEDIR/assets/models/json/Melbourne.json) \
        $$quote($$BASEDIR/assets/models/json/Mexico City.json) \
        $$quote($$BASEDIR/assets/models/json/Miami.json) \
        $$quote($$BASEDIR/assets/models/json/Montvideo.json) \
        $$quote($$BASEDIR/assets/models/json/Moscow.json) \
        $$quote($$BASEDIR/assets/models/json/New Delhi.json) \
        $$quote($$BASEDIR/assets/models/json/New York.json) \
        $$quote($$BASEDIR/assets/models/json/Paris.json) \
        $$quote($$BASEDIR/assets/models/json/Quito.json) \
        $$quote($$BASEDIR/assets/models/json/Rio De Janiero.json) \
        $$quote($$BASEDIR/assets/models/json/Rome.json) \
        $$quote($$BASEDIR/assets/models/json/San Francisco.json) \
        $$quote($$BASEDIR/assets/models/json/Santiago.json) \
        $$quote($$BASEDIR/assets/models/json/Seoul.json) \
        $$quote($$BASEDIR/assets/models/json/Sydney.json) \
        $$quote($$BASEDIR/assets/models/json/The City of Atlantis.json) \
        $$quote($$BASEDIR/assets/models/json/Tijuana.json) \
        $$quote($$BASEDIR/assets/models/json/Tokyo.json) \
        $$quote($$BASEDIR/assets/models/json/Toronto.json) \
        $$quote($$BASEDIR/assets/models/json/Waterloo.json) \
        $$quote($$BASEDIR/assets/models/json/weather.json) \
        $$quote($$BASEDIR/assets/models/max_model.xml) \
        $$quote($$BASEDIR/assets/models/sql/weatherguesser.db) \
        $$quote($$BASEDIR/assets/models/weather.xml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/appsettings.cpp) \
        $$quote($$BASEDIR/src/common/loadmodeldecorator.cpp) \
        $$quote($$BASEDIR/src/common/pulltorefresh.cpp) \
        $$quote($$BASEDIR/src/common/sqlheaderdataqueryex.cpp) \
        $$quote($$BASEDIR/src/common/weathererror.cpp) \
        $$quote($$BASEDIR/src/data/citydatasource.cpp) \
        $$quote($$BASEDIR/src/data/globalconnection.cpp) \
        $$quote($$BASEDIR/src/data/weatherdatasource.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/weatherguesserapp.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/appsettings.h) \
        $$quote($$BASEDIR/src/common/loadmodeldecorator.h) \
        $$quote($$BASEDIR/src/common/pulltorefresh.h) \
        $$quote($$BASEDIR/src/common/sqlheaderdataqueryex.h) \
        $$quote($$BASEDIR/src/common/weathererror.h) \
        $$quote($$BASEDIR/src/data/citydatasource.h) \
        $$quote($$BASEDIR/src/data/globalconnection.h) \
        $$quote($$BASEDIR/src/data/weatherdatasource.h) \
        $$quote($$BASEDIR/src/weatherguesserapp.h)
}

INCLUDEPATH += $$quote($$BASEDIR/src/common) \
    $$quote($$BASEDIR/src/data) \
    $$quote($$BASEDIR/src)

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/common/*.c) \
        $$quote($$BASEDIR/../src/common/*.c++) \
        $$quote($$BASEDIR/../src/common/*.cc) \
        $$quote($$BASEDIR/../src/common/*.cpp) \
        $$quote($$BASEDIR/../src/common/*.cxx) \
        $$quote($$BASEDIR/../src/data/*.c) \
        $$quote($$BASEDIR/../src/data/*.c++) \
        $$quote($$BASEDIR/../src/data/*.cc) \
        $$quote($$BASEDIR/../src/data/*.cpp) \
        $$quote($$BASEDIR/../src/data/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/images/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/images/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/images/*.qs) \
        $$quote($$BASEDIR/../assets/720x1280/images/menuicons/*.qml) \
        $$quote($$BASEDIR/../assets/720x1280/images/menuicons/*.js) \
        $$quote($$BASEDIR/../assets/720x1280/images/menuicons/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/*.js) \
        $$quote($$BASEDIR/../assets/720x720/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/WeatherPage/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/WeatherPage/*.js) \
        $$quote($$BASEDIR/../assets/720x720/WeatherPage/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/images/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/images/*.js) \
        $$quote($$BASEDIR/../assets/720x720/images/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/images/info/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/images/info/*.js) \
        $$quote($$BASEDIR/../assets/720x720/images/info/*.qs) \
        $$quote($$BASEDIR/../assets/Cities/*.qml) \
        $$quote($$BASEDIR/../assets/Cities/*.js) \
        $$quote($$BASEDIR/../assets/Cities/*.qs) \
        $$quote($$BASEDIR/../assets/Common/*.qml) \
        $$quote($$BASEDIR/../assets/Common/*.js) \
        $$quote($$BASEDIR/../assets/Common/*.qs) \
        $$quote($$BASEDIR/../assets/WeatherPages/*.qml) \
        $$quote($$BASEDIR/../assets/WeatherPages/*.js) \
        $$quote($$BASEDIR/../assets/WeatherPages/*.qs) \
        $$quote($$BASEDIR/../assets/WeatherPages/Weather/*.qml) \
        $$quote($$BASEDIR/../assets/WeatherPages/Weather/*.js) \
        $$quote($$BASEDIR/../assets/WeatherPages/Weather/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/big/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/big/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/big/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/small/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/small/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/small/*.qs) \
        $$quote($$BASEDIR/../assets/images/info/*.qml) \
        $$quote($$BASEDIR/../assets/images/info/*.js) \
        $$quote($$BASEDIR/../assets/images/info/*.qs) \
        $$quote($$BASEDIR/../assets/images/menuicons/*.qml) \
        $$quote($$BASEDIR/../assets/images/menuicons/*.js) \
        $$quote($$BASEDIR/../assets/images/menuicons/*.qs) \
        $$quote($$BASEDIR/../assets/images/pulltorefresh/*.qml) \
        $$quote($$BASEDIR/../assets/images/pulltorefresh/*.js) \
        $$quote($$BASEDIR/../assets/images/pulltorefresh/*.qs) \
        $$quote($$BASEDIR/../assets/models/*.qml) \
        $$quote($$BASEDIR/../assets/models/*.js) \
        $$quote($$BASEDIR/../assets/models/*.qs) \
        $$quote($$BASEDIR/../assets/models/json/*.qml) \
        $$quote($$BASEDIR/../assets/models/json/*.js) \
        $$quote($$BASEDIR/../assets/models/json/*.qs) \
        $$quote($$BASEDIR/../assets/models/sql/*.qml) \
        $$quote($$BASEDIR/../assets/models/sql/*.js) \
        $$quote($$BASEDIR/../assets/models/sql/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
