<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0">
<context>
    <name>pushcollector::RegisterService</name>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="82"/>
        <source>Error: The token from the create channel was null, empty, or longer than 40 characters in length.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="88"/>
        <source>Error: The OS version or device model of the BlackBerry was invalid.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="91"/>
        <source>Error: The application ID specified in the configuration settings could not be found, or it was found to be inactive or expired.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="94"/>
        <source>Error: The subscriber ID generated by the Push Initiator (based on the username and password specified) was null or empty, longer than 42 characters in length, or matched the &apos;push_all&apos; keyword.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="98"/>
        <source>Error: The Push Initiator application has the bypass subscription flag set to true (so no subscribe is allowed).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="101"/>
        <source>Error: The username or password specified was incorrect.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="107"/>
        <source>Error: A CPSubscriptionFailureException was thrown by the onSubscribeSuccess method of the implementation being used of the ContentProviderSubscriptionService interface.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="114"/>
        <source>Error: The type specified was null, empty, or not one of &apos;public&apos; or &apos;bds&apos;, or invalid for the push application type.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="117"/>
        <source>Error: General error (i.e. rc=-9999).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/RegisterService.cpp" line="119"/>
        <source>Error: Unknown error code: %0.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>pushcollector::UnregisterService</name>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="87"/>
        <source>Error: The application ID specified in the configuration settings could not be found, or it was found to be inactive or expired.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="90"/>
        <source>Error: The subscriber (matching the username and password specified) could not be found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="93"/>
        <source>Error: The subscriber ID generated by the Push Initiator (based on the username and password specified) was null or empty, longer than 42 characters in length, or matched the &apos;push_all&apos; keyword.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="97"/>
        <source>Error: The Push Initiator application has the bypass subscription flag set to true (so no unsubscribe is allowed).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="100"/>
        <source>Error: The username or password specified was incorrect.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="106"/>
        <source>Error: A CPSubscriptionFailureException was thrown by the onUnsubscribeSuccess method of the implementation being used of the ContentProviderSubscriptionService interface.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="110"/>
        <source>Error: General error (i.e. rc=-9999).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/service/UnregisterService.cpp" line="112"/>
        <source>Error: Unknown error code: %0.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
