# Auto-generated by IDE. Changes by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/bucketbbm/bucketbbmmanager.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/global.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/profilebox.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/profilemessage.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/registrationhandler.cpp) \
                 $$quote($$BASEDIR/src/bucketdata/bucketmodel.cpp) \
                 $$quote($$BASEDIR/src/bucketdata/bucketsettings.cpp) \
                 $$quote($$BASEDIR/src/bucketlistapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/bucketbbm/bucketbbmmanager.h) \
                 $$quote($$BASEDIR/src/bucketbbm/global.h) \
                 $$quote($$BASEDIR/src/bucketbbm/profilebox.h) \
                 $$quote($$BASEDIR/src/bucketbbm/profilemessage.h) \
                 $$quote($$BASEDIR/src/bucketbbm/registrationhandler.h) \
                 $$quote($$BASEDIR/src/bucketdata/bucketmodel.h) \
                 $$quote($$BASEDIR/src/bucketdata/bucketsettings.h) \
                 $$quote($$BASEDIR/src/bucketlistapp.h)

    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/bucketbbm/bucketbbmmanager.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/global.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/profilebox.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/profilemessage.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/registrationhandler.cpp) \
                 $$quote($$BASEDIR/src/bucketdata/bucketmodel.cpp) \
                 $$quote($$BASEDIR/src/bucketdata/bucketsettings.cpp) \
                 $$quote($$BASEDIR/src/bucketlistapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/bucketbbm/bucketbbmmanager.h) \
                 $$quote($$BASEDIR/src/bucketbbm/global.h) \
                 $$quote($$BASEDIR/src/bucketbbm/profilebox.h) \
                 $$quote($$BASEDIR/src/bucketbbm/profilemessage.h) \
                 $$quote($$BASEDIR/src/bucketbbm/registrationhandler.h) \
                 $$quote($$BASEDIR/src/bucketdata/bucketmodel.h) \
                 $$quote($$BASEDIR/src/bucketdata/bucketsettings.h) \
                 $$quote($$BASEDIR/src/bucketlistapp.h)

    }

}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/bucketbbm/bucketbbmmanager.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/global.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/profilebox.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/profilemessage.cpp) \
                 $$quote($$BASEDIR/src/bucketbbm/registrationhandler.cpp) \
                 $$quote($$BASEDIR/src/bucketdata/bucketmodel.cpp) \
                 $$quote($$BASEDIR/src/bucketdata/bucketsettings.cpp) \
                 $$quote($$BASEDIR/src/bucketlistapp.cpp) \
                 $$quote($$BASEDIR/src/main.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/bucketbbm/bucketbbmmanager.h) \
                 $$quote($$BASEDIR/src/bucketbbm/global.h) \
                 $$quote($$BASEDIR/src/bucketbbm/profilebox.h) \
                 $$quote($$BASEDIR/src/bucketbbm/profilemessage.h) \
                 $$quote($$BASEDIR/src/bucketbbm/registrationhandler.h) \
                 $$quote($$BASEDIR/src/bucketdata/bucketmodel.h) \
                 $$quote($$BASEDIR/src/bucketdata/bucketsettings.h) \
                 $$quote($$BASEDIR/src/bucketlistapp.h)

    }

}

INCLUDEPATH +=  $$quote($$BASEDIR/src/bucketdata) \
         $$quote($$BASEDIR/src) \
         $$quote($$BASEDIR/src/bucketbbm)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../assets/*.qml)

}

TRANSLATIONS =  $$quote($${TARGET}.ts)

